"""PyTorch code generator for ChimeraLang."""
from __future__ import annotations

_LAYER_MAP = {
    "Dense": "nn.Linear", "Linear": "nn.Linear", "ReLU": "nn.ReLU",
    "GELU": "nn.GELU", "Softmax": "nn.Softmax", "Sigmoid": "nn.Sigmoid",
    "Tanh": "nn.Tanh", "Dropout": "nn.Dropout", "LayerNorm": "nn.LayerNorm",
    "BatchNorm": "nn.BatchNorm1d", "Embedding": "nn.Embedding",
    "Conv2d": "nn.Conv2d", "Flatten": "nn.Flatten", "Attention": "nn.MultiheadAttention",
}
_OPTIM_MAP = {
    "Adam": "torch.optim.Adam", "AdamW": "torch.optim.AdamW",
    "SGD": "torch.optim.SGD", "RMSprop": "torch.optim.RMSprop", "LAMB": "torch.optim.Adam",
}
_LOSS_MAP = {
    "CrossEntropy": "nn.CrossEntropyLoss", "MSE": "nn.MSELoss",
    "BCE": "nn.BCELoss", "KLDivergence": "nn.KLDivLoss", "NLL": "nn.NLLLoss",
}


class PyTorchCodegen:
    def __init__(self) -> None:
        self._constitutions: dict = {}
        self._indent = 0
        self._lines: list = []

    @staticmethod
    def _node_kind(decl: object) -> str:
        """Return the canonical node kind regardless of name prefix (e.g. _ModelDecl -> ModelDecl)."""
        name = type(decl).__name__
        # Strip leading underscores so mock classes in tests match real AST classes
        return name.lstrip("_")

    def generate(self, program: object) -> str:
        self._lines = []
        self._constitutions = {}
        # collect constitutions first
        for decl in getattr(program, "declarations", []):
            if self._node_kind(decl) == "ConstitutionDecl":
                self._constitutions[decl.name] = decl
        # header
        self._emit("# AUTO-GENERATED BY CHIMERALANG COMPILER — DO NOT EDIT")
        self._emit("import torch")
        self._emit("import torch.nn as nn")
        self._emit("from torch.utils.data import DataLoader")
        self._emit("try:")
        self._emit("    from chimera_runtime import BeliefTracker, GuardLayer, ConstitutionLayer")
        self._emit("except ImportError:")
        self._emit("    BeliefTracker = GuardLayer = ConstitutionLayer = None")
        self._emit("")
        for decl in getattr(program, "declarations", []):
            cls_name = self._node_kind(decl)
            if cls_name == "ImportStmt":
                self._gen_import(decl)
            elif cls_name == "ModelDecl":
                self._gen_model(decl)
            elif cls_name == "TrainStmt":
                self._gen_train(decl)
            elif cls_name == "ConstitutionDecl":
                self._emit(f"# Constitution: {decl.name}")
                for p in decl.principles:
                    self._emit(f"#   - {p}")
                self._emit("")
        return "\n".join(self._lines)

    def _gen_import(self, node: object) -> None:
        symbols = ", ".join(node.symbols) if node.symbols else "*"
        self._emit(f"# import {node.module} {{ {symbols} }}")

    def _gen_model(self, model: object) -> None:
        self._emit(f"class {model.name}(nn.Module):")
        with self._indented():
            self._emit("def __init__(self):")
            with self._indented():
                self._emit("super().__init__()")
                for layer in model.layers:
                    self._gen_layer_init(layer, model)
                if getattr(model, "uncertainty", "none") in ("epistemic", "aleatoric", "full"):
                    self._emit(f'self._belief_tracker = BeliefTracker(mode="{model.uncertainty}") if BeliefTracker else None')
                const_name = getattr(model, "constitution", None)
                if const_name and const_name in self._constitutions:
                    c = self._constitutions[const_name]
                    self._emit(f"self._constitution = ConstitutionLayer({c.principles!r}, rounds={c.critique_rounds}) if ConstitutionLayer else None")
            self._emit("")
            self._emit("def forward(self, x):")
            with self._indented():
                self._gen_forward_body(model)
        self._emit("")

    def _gen_layer_init(self, layer: object, model: object) -> None:
        kind = layer.kind
        if kind == "MoE":
            n = layer.config.get("n_experts", 8)
            k = layer.config.get("top_k", 2)
            d = layer.config.get("expert_dim", 4096)
            self._emit(f"self.{layer.name}_experts = nn.ModuleList([nn.Linear({d}, {d}) for _ in range({n})])")
            self._emit(f"self.{layer.name}_router = nn.Linear({d}, {n})")
            self._emit(f"self._{layer.name}_top_k = {k}")
            return
        pt_cls = _LAYER_MAP.get(kind, f"nn.Identity  # unknown: {kind}")
        if kind in ("Dense", "Linear", "Embedding") and layer.in_dim and layer.out_dim:
            self._emit(f"self.{layer.name} = {pt_cls}({layer.in_dim}, {layer.out_dim})")
        elif kind == "Dropout":
            p = layer.config.get("p", 0.1)
            self._emit(f"self.{layer.name} = {pt_cls}(p={p})")
        elif kind == "LayerNorm":
            d = layer.out_dim or layer.in_dim or 768
            self._emit(f"self.{layer.name} = {pt_cls}({d})")
        else:
            self._emit(f"self.{layer.name} = {pt_cls}()")
        if getattr(layer, "repeat", 1) > 1:
            last = self._lines.pop()
            expr = last.strip().split(" = ", 1)[1]
            self._emit(f"self.{layer.name} = nn.ModuleList([{expr} for _ in range({layer.repeat})])")

    def _gen_forward_body(self, model: object) -> None:
        layers = getattr(model, "layers", [])
        if not layers:
            self._emit("return x")
            return
        prev = "x"
        for layer in layers:
            if layer.kind == "MoE":
                name = layer.name
                nxt = f"h_{name}"
                self._emit(f"_router_logits = self.{name}_router({prev})")
                self._emit(f"_topk = torch.topk(_router_logits, self._{name}_top_k, dim=-1)")
                self._emit(f"{nxt} = torch.zeros_like({prev})")
                self._emit(f"for _i, _expert in enumerate(self.{name}_experts):")
                self._emit(f"    _mask = (_topk.indices == _i).any(dim=-1, keepdim=True).float()")
                self._emit(f"    {nxt} = {nxt} + _mask * _expert({prev})")
                prev = nxt
            elif getattr(layer, "repeat", 1) > 1:
                nxt = f"h_{layer.name}"
                self._emit(f"{nxt} = {prev}")
                self._emit(f"for _layer in self.{layer.name}:")
                self._emit(f"    {nxt} = _layer({nxt})")
                prev = nxt
            else:
                nxt = f"h_{layer.name}"
                self._emit(f"{nxt} = self.{layer.name}({prev})")
                prev = nxt
        const_name = getattr(model, "constitution", None)
        if const_name and const_name in self._constitutions:
            self._emit(f"if self._constitution is not None: {prev} = self._constitution.apply({prev})")
        if getattr(model, "uncertainty", "none") in ("epistemic", "aleatoric", "full"):
            self._emit(f"if self._belief_tracker is not None: self._belief_tracker.record({prev})")
        self._emit(f"return {prev}")

    def _gen_train(self, train: object) -> None:
        model_var = train.model_name.lower()
        opt = getattr(train, "optimizer", None)
        loss = getattr(train, "loss", None)
        opt_cls = _OPTIM_MAP.get(getattr(opt, "name", "Adam"), "torch.optim.Adam")
        loss_cls = _LOSS_MAP.get(getattr(loss, "name", "CrossEntropy"), "nn.CrossEntropyLoss")
        opt_params = ", ".join(f"{k}={v!r}" for k, v in getattr(opt, "params", {}).items())
        epochs = getattr(train, "epochs", 10)
        batch_size = getattr(train, "batch_size", 32)
        dataset = getattr(train, "dataset", "train_data")
        self._emit(f"# Training: {train.model_name} on {dataset}")
        self._emit(f"{model_var} = {train.model_name}()")
        self._emit(f"_optimizer = {opt_cls}({model_var}.parameters(), {opt_params})")
        self._emit(f"_criterion = {loss_cls}()")
        self._emit("")
        self._emit(f"for epoch in range({epochs}):")
        with self._indented():
            self._emit(f"for _x, _y in DataLoader({dataset}, batch_size={batch_size}, shuffle=True):")
            with self._indented():
                self._emit(f"_pred = {model_var}(_x)")
                self._emit("_loss = _criterion(_pred, _y)")
                self._emit("_optimizer.zero_grad()")
                self._emit("_loss.backward()")
                self._emit("_optimizer.step()")
            self._emit(f'print(f"Epoch {{epoch+1}}/{epochs} loss={{_loss.item():.4f}}")')
        self._emit("")

    def _emit(self, line: str) -> None:
        self._lines.append("    " * self._indent + line if line else "")

    class _Indent:
        def __init__(self, cg): self._cg = cg
        def __enter__(self): self._cg._indent += 1; return self
        def __exit__(self, *_): self._cg._indent -= 1

    def _indented(self): return PyTorchCodegen._Indent(self)
